var CWHtmlStructure={getBody:function(a,d){a=encodeURI(a);d=encodeURI(d);var c="cw-logo";CWPDFReaderConfig.readerMode==CWPDFReaderMode.Publisher&&(c="publisher-logo");var b="display:none;",e="";CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Library&&CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Drive&&(b="",e="display:none;");var f=CWPDFReaderConfig.readerMode===CWPDFReaderMode.Drive,g=CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Library&&CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Drive;CwH.partials=
CwH.templates;return(0,CwH.templates.getBody)({smallCanvasClass:"",imageUrl:a,logoClass:c,modeDrive:f,modeNotDriveLibrary:g,fullscreenBtnStyle:b,restoreBtnStyle:e,CWPDFReaderConfig:{cwURL:CWPDFReaderConfig.cwURL},pdfUrl:d})},getCommentBody:function(a){return(CWPDFReaderConfig.isDesktopMode()||CWPDFReaderConfig.readerMode==CWPDFReaderMode.Chrome?CwH.templates.getCommentBody:window.parent.CwH.templates.getCommentBody)({cmtId:a.cmtId,cmtText:a.cmtText,cmtClass:a.cmtClass,timeDiff:a.timeDiff,cmtPage:a.cmtPage,
minY:a.minY})},getSplashScreen:function(a){CwH.partials=CwH.templates;var d=CwH.templates.getSplash,c=!CWPDFReaderConfig.isCoreMode();return d({classSpec:a,notCoreMode:c,loaderClass:c?"cw-loader":""})},getPopupBody:function(a,d){return(0,CwH.templates.getPopupBody)({getRecHtml:a,contextCont:d})},getDownloadPopup:function(a,d){var c=JSON.parse(JSON.stringify(a));/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{4})([=]{1,2})?$/.test(c.title)&&(c.title=Base64.decode(c.title));
var b=btoa(c.pdfLink+"@@@0");return(0,CwH.templates.getDownloadPopup)({metaData:c,encodedHash:b,publisherOpt:d})},getReferenceTip:function(a,d){var c=window.parent.CwH.templates.getReferenceTip,b={ref:a};d&&(b.tip=!0);return c(b)},getAuthorSideBarLi:function(a,d){1<a.pubs&&(a.pubsPlus=!0);1<a.coCount&&(a.coAuthPlus=!0);1<d?CwZ(".cw-authorTab .numberOfAuthors span").text(d+" Authors"):CwZ(".cw-authorTab .numberOfAuthors span").text(d+" Author");var c=a.fullName.toUpperCase().split(/[\s.]+/),b="",b=
1==c.length?c[0].charAt(0):c[0].charAt(0)+c[c.length-1].charAt(0);a.nameInitials=b;return(CWPDFReaderConfig.isDesktopMode()||CWPDFReaderConfig.readerMode==CWPDFReaderMode.Chrome?CwH.templates.getAuthorSideBarLi:window.parent.CwH.templates.getAuthorSideBarLi)({author:a,domainURL:CWPDFReaderConfig.cwURL})},getAuthorSidebarWidget:function(a,d,c,b){return(0,CwH.templates.getAuthorSidebarWidget)({nameInitials:a,thisAuth:d,pubs:c,co_authors:b,author:d,domainURL:"https://"+cPDF.domain})},getHead:function(a,
d,c){var b="lib/jquery_ireader.js lib/raven.js lib/blob.js lib/jDialog.js lib/jDialogFunc.js lib/compatibility.js lib/pdf.js lib/svg.min.js lib/svg.filter.js lib/zlib_and_gzip.min.js lib/pdf_find_controller.js lib/tether.js extension/html_structure.js publisher/iframe_pub.js ../extraction/authortooltip/js/00_main.js main/00_config.js main/01_logger.js main/02_cw_codec.js main/03_utilities.js /main/03b_pdfreader.js".split(" "),e=[];CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome?b.push("main/04a_pdfreader_chrome.js"):
CWPDFReaderConfig.readerMode===CWPDFReaderMode.Library?b.push("main/04a_pdfreader_library.js"):CWPDFReaderConfig.readerMode===CWPDFReaderMode.Drive?b.push("main/04a_pdfreader_drive.js"):CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Publisher&&CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Webimporter||b.push("main/04a_pdfreader_publisher.js");b.push("main/05_annotations.js");b.push("main/06_page.js");CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Publisher&&b.push("main/07_datacenter.js");b.push("main/08_textlayer.js");
b.push("main/09_comments.js");b.push("main/10_shape.js");CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome?e.push("reader_chrome.css"):e.push("reader_web.css");return(0,CwH.templates.getHead)({scripts:b,css:e,jsPath:a,cssPath:d,version:c})},getSignupDialog:function(){return(CWPDFReaderConfig.isDesktopMode()||CWPDFReaderConfig.readerMode==CWPDFReaderMode.Chrome?CwH.templates.getSignupDialog:window.parent.CwH.templates.getSignupDialog)({})},getFeedbackForm:function(){return(CWPDFReaderConfig.isDesktopMode()||
CWPDFReaderConfig.readerMode==CWPDFReaderMode.Chrome?CwH.templates.getFeedbackForm:window.parent.CwH.templates.getFeedbackForm)({})},getUserToDD:function(a,d){return(CWPDFReaderConfig.isDesktopMode()||CWPDFReaderConfig.readerMode==CWPDFReaderMode.Chrome?CwH.templates.getUserToDD:window.parent.CwH.templates.getUserToDD)({uid:a,divText:d})},getCoreDialog:function(){return(CWPDFReaderConfig.isDesktopMode()||CWPDFReaderConfig.readerMode==CWPDFReaderMode.Chrome?CwH.templates.getCoreDialog:window.parent.CwH.templates.getCoreDialog)({})},
getSupplementLiHtml:function(a,d){return(CWPDFReaderConfig.isDesktopMode()||CWPDFReaderConfig.readerMode==CWPDFReaderMode.Chrome?CwH.templates.getSupplementLiHtml:window.parent.CwH.templates.getSupplementLiHtml)({key:a,finalFile:d})},insertButtonsOnPage:function(a){if(CWPDFReader.pubSolInjected)return!0;var d="hidden"!=CwZ.trim(a["class"]),c="",b=!1,e=!1,f,g=!1;publisher&&(b=!!~a["class"].trim().indexOf("-list"),e=!!~a["class"].trim().indexOf("-detail"),f=publisher.buttonStyle,g=(b||e)&&"popup"==
f);if(d)if("popup"==f)if(0==CwZ("#preloadCwZSprite").length&&CwZ("body").append('<div id="preloadCwZSprite"></div>'),e)try{return a.buttonCB(a.metaData),!1}catch(h){return!1}else{if(b)try{return a.buttonCB(a.metaData),!1}catch(k){return!1}}else d=!0,c="View & Annotate PDF",e="Add to colwiz",a||(a={pdfUrl:"",index:0,inline:!1,"class":""}),CWPDFReader.colwizOptions&&(d=CWPDFReader.colwizOptions.showAddToColwiz),b="",CWPDFReaderConfig.readerMode===CWPDFReaderMode.Webimporter&&(b='style="display:none !important"',
e=CWPDFReaderConfig.pubModeBtnsTxt,c=e.view,e=e.add),CWPDFReaderConfig.readerMode===CWPDFReaderMode.Publisher&&(a["class"]+=" pub-mode",e=CWPDFReaderConfig.pubModeBtnsTxt,c=e.view,e=e.add),CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome&&(c=CWPDFReaderConfig.extModeBtnsTxt.view),f="",a.inline&&!g&&(f=" cw-inline"),f+=" "+a["class"],g&&(b='style="display:none"'),g=CWHtmlStructure.generateReaderHash(a.pdfUrl,a.index),c=(0,CwH.templates.getButtons)({classes:f,style:b,generatedHash:g,index:a.index,
url:a.pdfUrl,viewBtnTxt:c,hoverBtnText:CWPDFReaderConfig.pubModeBtnsTxt.viewHover,showAddButton:d,addBtnTxt:e,addHoverBtnText:CWPDFReaderConfig.pubModeBtnsTxt.addHover});return c},generateReaderHash:function(a,d,c){a=a+"@@@"+d;c&&(a+="@@@forwarded");return a=Base64.encode(a)},decodeReaderHash:function(a){a=Base64.decode(a).split("@@@");var d=[];d.PDFURL=a[0];d.INDEX=a[1];a[2]&&"forwarded"==a[2]&&(d.FORWARDED=!0);return d}};
"undefined"!==typeof CwH&&CwH.registerHelper("ifC",function(a,d,c,b){switch(d){case "==":return a==c?b.fn(this):b.inverse(this);case "===":return a===c?b.fn(this):b.inverse(this);case "<":return a<c?b.fn(this):b.inverse(this);case "<=":return a<=c?b.fn(this):b.inverse(this);case ">":return a>c?b.fn(this):b.inverse(this);case ">=":return a>=c?b.fn(this):b.inverse(this);case "&&":return a&&c?b.fn(this):b.inverse(this);case "||":return a||c?b.fn(this):b.inverse(this);default:return b.inverse(this)}});
